# scan_filter_chain:
  # - name: shadows
  #  type: ScanShadowsFilter
  #  params:
  #    min_angle: 0
  #    max_angle: 180
  #    neighbors: 20
  #    window: 1
  # - name: dark_shadows
  #   type: LaserScanIntensityFilter
  #   params: 
  #     lower_threshold: 100
  #     upper_threshold: 10000
  #     disp_histogram: 0
  # - type: LaserArrayFilter
  #   name: laser_median_filter
  #   params: 
  #     range_filter_chain:
  #       - name: median_5
  #         type: MultiChannelMedianFilterFloat 
  #         params:
  #           number_of_observations: 10
  #           unused: 15
  #     intensity_filter_chain:
  #       - name: median_5
  #         type: MultiChannelMedianFilterFloat 
  #         params:
  #           number_of_observations: 10
  #           unused: 15